// models/Notification.js
// Purpose: an in-app notification for one user, generated by system events
// (new bid, bid accepted, project completed, review received).

const mongoose = require("mongoose");

const notificationSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true, // who receives this notification
    },
    type: {
      type: String,
      enum: ["new_bid", "bid_accepted", "project_completed", "review_received"],
      required: true,
    },
    message: {
      type: String,
      required: true,
    },
    relatedProject: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Project",
      default: null,
    },
    isRead: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Notification", notificationSchema);
